### ISSUE TITLE
Invalid polygon data, triangulation failed bug

### ISSUE THREAD

**Issue by badduck32** [Pedrokkkkkk/Godot-Touch-Acessibility#1]
I have tried turning on the addon on the Godot editor on my Android phone, but it doesn't seem to work. I get an error saying "Invalid polygon data, triangulation failed."
I have provided a screenshot to maybe help you solve the issue.
I also wanted to say nice job on the plugin!! I'm excited to see it working in action 😄 
![image](https://user-images.githubusercontent.com/44337504/168425190-c2f3063d-537c-4046-8074-a23eb7a53b43.png)

**Comment by badduck32** [comment]
I have tried running the plugin again and it's possible that this error message is unrelated to this plugin. Sadly it doesn't seem like the plugin does anything on my device, even though it says it's enabled

**Comment by Pedrokkkkkk** [comment]
is it related to a bug in the plugin? if its about the engine, report at godot github, no way i can solve this if not related to my plugin. Thanks for using the plugin @badduck32

**Comment by Pedrokkkkkk** [comment]
you need to enable the plugin first at your project settings, there will be a dock in the right bottom panel showing you the plugin utils, also a keyboard tab is in the bottom panel, the keyboard only works at script editor @badduck32

**Comment by badduck32** [comment]
@Pedrokkkkkk Yes, I have found the panel and the plugin seems to work like intended!! It looks great and I'm already enjoying using it :))
