### ISSUE TITLE
Upload source code on the repository itself

### ISSUE THREAD

**Issue by Calinou** [Pedrokkkkkk/Godot-Touch-Acessibility#2]
The add-on code is only contained within a ZIP on GitHub Releases right now. Could you also push the source code to the repository itself? This would make installation via `git clone` easier. Thanks in advance :slightly_smiling_face: 

See https://github.com/Calinou/godot-addon-template for an example structure you can use.

**Comment by Pedrokkkkkk** [comment]
> The add-on code is only contained within a ZIP on GitHub Releases right now. Could you also push the source code to the repository itself? This would make installation via `git clone` easier. Thanks in advance 🙂
> 
> See https://github.com/Calinou/godot-addon-template for an example structure you can use.

thanks for warning calinou, i will provide the source code now
